
const express = require('express');
const bodyParser = require('body-parser');
const { default: mongoose } = require('mongoose');
const { default: slugify } = require('slugify');
const Club = require('../models/club.model');
const User = require('../models/user.model');
const { getUser, getClub } = require('./miscallenous');
const {
  BadRequest, Conflict, NotFound, GeneralError, Unauthorized, Forbidden
} = require('../middleware/error');
const { checkExist } = require('./exist');


/**
 * Define a router for this collection of api endpoints
 * @type {express.Router}
 */
const router = express.Router();
/**
 * Use json parsing middleware
 * @type {import('body-parser').json()}
 * */
const jsonParser = bodyParser.json();

/**
 * Creates a new club through the '/club/create' endpoint.
 * Errors thrown during creation will be passed to the
 * Error Handler middleware using @property {next}
 * @see handleErrors
 *
 *
 * @property {string} name                      -> Required field in request body,
 *                                                 denotes name of the club
 * @property {object} socialsObject             -> Assembled object from the instagram,
 *                                                 google_classroom_code and signup_link fields
 * @property {string} instagram                 -> instagram link of the club
 * @property {string} google_classroom_code     -> the club's google classroom code to join
 * @property {string} signup_link               -> the club's link to a google form or
 *                                                 somewhere for users to sign up
 * @property {string} description               -> The 'about me' section of the club
 * @property {string} clubfest_link             -> Link to the club's promotion video
 *
 * @returns {club} -> JSON representation of the created club object from mongodb
 */
router.post('/create', jsonParser, async (req, res, next) => {
  const newClubFields = {};
  const socialsObject = {};

  try {
    /*
     * Make sure these fields are only added to the newClubFields if they exist.
     * Otherwise they are left blank or they will not be
     */
    if (req.body.name) {
      newClubFields.name = req.body.name;
      const newSlug = slugify(req.body.name, { lower: true });
      newClubFields.slug = newSlug;
    } else throw new BadRequest('Missing required field: Name');
    if (req.body.instagram) socialsObject.instagram = req.body.instagram;
    if (req.body.google_classroom_code) {
      socialsObject.google_classroom_code = req.body.google_classroom_code;
    }
    if (req.body.signup_link) socialsObject.signup_link = req.body.signup_link;
    if (req.body.description) {
      if (req.body.description.length < 150) newClubFields.description = req.body.description;
      else throw new BadRequest('Character limit exceeded');
    } else throw new BadRequest('Missing required field: Description');


    if (checkExist(req.body.teacher)) {
      const teacher = await getUser('_id', req.body.teacher);
      if (teacher.account_type !== 'teacher') throw new Unauthorized('Only teachers are allowed to take this role');
      else newClubFields.teacher = req.body.teacher;
    }
    else throw new BadRequest('Missing required field: Teacher');

    if (req.body.clubfest_link) newClubFields.clubfest_link = req.body.clubfest_link;

    // If either of those social objects exist, then add the socialObject to newClubFields
    if (socialsObject.google_classroom_code
      || socialsObject.instagram || socialsObject.signup_link) {
      newClubFields.socials = socialsObject;
    }

    // events and posts fields that are auto updated each time a new post to the club is made
    newClubFields.events = 0;
    newClubFields.posts = 0;

    /**
     * Fetch whether the club exists or not using the slug
     *
     * @property {string} slug -> The autogenerated identification
     *                            that was created from the club name
     * @returns {Club || null}         -> The club object or null
     */
    const clubExists = await Club.exists({ slug: newClubFields.slug });

    /* Throw a Conflict error if the club exists */
    if (clubExists !== null) throw new Conflict('Resource Conflict: Name is taken already');
    else {
      /**
       * Using mongoose, create a new Club with the Club schema
       *
       * @see Club
       * @returns {Club} club -> the club object or an error
       */
      Club.create(newClubFields, (err, club) => {
        if (err) throw new GeneralError(`${err}`, `${err}`);
        else res.status(201).send(club);
      });
    }
  } catch (err) { // If any error was thrown pass it to the middleware
    next(err);
  }
});

/**
 * Delete a club by their slug
 *
 * @property {string} slug -> slug is the unique identifier from a club's name
 * @return {Club} club     -> the json representation of the just-deleted club
 */
 
router.delete('/slug/:slug/delete', jsonParser, async (req, res, next) => {
  const filterSlug = req.params.slug;

  try {
    /**
     * Query using mongodb's findOneAndDelete() to find the club object and delete it
     * @return {Club} club -> the json representation of the just-deleted club
     */
    Club.findOneAndDelete({ slug: filterSlug }, (err, club) => {
      if (err) { // If there's an error through a BadRequest 400 with the error
        throw new BadRequest('Bad Request', `${err}`);
      } else if (club === null) throw new NotFound(`Not found: ${filterSlug}`);
      else res.status(200).send(club);
    });
  } catch (err) { // If any error was thrown pass it to the middleware
    next(err);
  }
});

/**
 * Filter clubs through the Club object id
 *
 * @property {string} id -> id is the unique identifier autogenerated by mongodb
 * @return {Club} club   -> the club that contains this id
 */
router.get('/club/id/:id', jsonParser, async (req, res, next) => {
  const filterId = req.params.id; // retrieve id from the param
  try {
    /**
     * Query using mongoose find to find the club object
     * @return {Club} club -> the json representation of the club
     */
    Club.find({ _id: mongoose.mongo.ObjectId(filterId) }, (err, club) => {
      if (!err) { // If there's an error through a BadRequest 400 with the error
        res.status(200).send(club);
      } else {
        throw new BadRequest('Bad Request', `${err}`);
      }
    });
  } catch (err) { // If any error was thrown pass it to the middleware
    next(err);
  }
});

/**
 * Filter clubs through the Club object slug
 *
 * @property {string} slug -> slug is the unique identifier from a club's name
 * @return {Club} club     -> the club that contains this slug
 */

router.get('/slug/:slug', jsonParser, async (req, res, next) => {
  const filterSlug = req.params.slug;

  try {
    /**
     * Query using mongoose find to find the club object
     * @return {Club} club -> the json representation of the club
     */
    Club.find({ slug: filterSlug }, (err, club) => {
      if (err) throw new BadRequest('Bad Request', `${err}`); // If there's an error through a BadRequest 400 with the error
      else if (club.length === 0) { // If the club doesn't exist, throw a NotFound error
        throw new NotFound(`Not found: ${filterSlug}`);
      } else res.status(200).send(club);
    });
  } catch (err) { // If any error was thrown pass it to the middleware
    next(err);
  }
});

/**
 * Retrieve all clubs
 *
 * @return {Club} clubs -> An array of Club objects that is all the clubs in the database
 */
router.get('/all', jsonParser, async (req, res, next) => {
  try {
    /**
     * Query using mongoose find without any conditions to get all club objects
     * @return {Club} club -> the json representation of the club
     */
    Club.find({}, (err, clubs) => {
      if (!err) { // If there's an error through a BadRequest 400 with the error
        res.status(200).send(clubs);
      } else {
        throw new BadRequest('Bad Request', `${err}`);
      }
    });
  } catch (err) { // If any error was thrown pass it to the middleware
    next(err);
  }
});

/**
 * Updates a club object but does NOT update teacher or execs.
 * Those go through a separate endpoint:
 *
 * @see "/club/slug/:slug/executives/add"
 * @see "/club/slug/:slug/teacher/add"
 *
 * @property {string} slug                      -> slug of the club object to be updated
 * @property {string} name                      -> Required field in request body,
 *                                                 denotes name of the club
 * @property {object} socialsObject             -> Assembled object from the instagram,
 *                                                 google_classroom_code and signup_link fields
 * @property {string} instagram                 -> instagram link of the club
 * @property {string} google_classroom_code     -> the club's google classroom code to join
 * @property {string} signup_link               -> the club's link to a google form or
 *                                                 somewhere for users to sign up
 * @property {string} description               -> The 'about me' section of the club
 * @property {string} clubfest_link             -> Link to the club's promotion video
 *
 * @returns {club} -> JSON representation of the updated club object from mongodb
 *
 */
router.put('/slug/:slug/update', jsonParser, async (req, res, next) => {
  const filterSlug = req.params.slug;
  const updateFields = {};
  const socialsObject = {};
  try {
    /*
     * Check if these fields exist, and if they do,
     * then add them to the update object to be updated
     */
    if (req.body.name) {
      updateFields.name = req.body.name;
      const newSlug = slugify(req.body.name, { lower: true });
      updateFields.slug = newSlug;
    }
    if (req.body.instagram) socialsObject.instagram = req.body.instagram;
    if (req.body.google_classroom_code) {
      socialsObject.google_classroom_code = req.body.google_classroom_code;
    }
    if (req.body.signup_link) socialsObject.signup_link = req.body.signup_link;
    if (req.body.description) updateFields.description = req.body.description;
    if (req.body.clubfest_link) updateFields.clubfest_link = req.body.clubfest_link;

    if (socialsObject.google_classroom_code
      || socialsObject.instagram || socialsObject.signup_link) {
      updateFields.socials = socialsObject;
    }

    /**
     * Use mongodb's query findOneAndUpdate() to find the club
     * object with the slug and update it using the update fields
     *
     * @property {object} queryOptions    -> mongoose query options to
     *                                       return the newly update object
     * @return {Club} club                -> the new club object that was queried and updated
     */
    Club.findOneAndUpdate({ slug: filterSlug }, updateFields, { new: true }, (err, club) => {
      if (err) throw new GeneralError(`${err}`, `${err}`);
      else if (club === null) throw new NotFound(`Not found: ${filterSlug}`);
      else {
        res.status(200).send(club);
      }
    });
  } catch (err) {
    next(err);
  }
});

/**
 * Update the club executives array in a particular club.
 * Pass a slug in the param to query that specific club
 *
 * @property {string} slug -> slug of the club object to be updated
 * @return {Club} club -> the new club object that is updated
 */
router.put('/slug/:slug/executives/add', jsonParser, async (req, res, next) => {
  const filterSlug = req.params.slug;
  let updateFieldExecutive; // If there contains an executive use this to store
  try {
    if (req.body.executive) updateFieldExecutive = req.body.executive;
    Club.findOneAndUpdate(
      { slug: filterSlug },
      { $addToSet: { execs: updateFieldExecutive } }, // Use mongoose operator to insert this club
      // executive element into the array of execs
      { new: true }, // enable return the newly updated club object
      (err, club) => {
        if (err) {
          throw new BadRequest('Bad Request', `${err}`);
        } else if (club === null) throw new NotFound(`Not found: ${filterSlug}`);
        else res.status(200).send(club);
      },
    );
  } catch (err) {
    next(err);
  }
});

/**
 * Update the club teachers array in a particular club.
 * Pass a slug in the param to query that specific club
 *
 * @property {string} slug -> slug of the club object to be updated
 * @return {Club} club -> the new club object that is updated
 */
router.put('/club/slug/:slug/teacher/add', jsonParser, async (req, res, next) => {
  const filterSlug = req.params.slug;
  let updateFieldTeacher; // If there contains a teacher use this to store
  if (req.body.teacher) updateFieldTeacher = req.body.teacher;
  try {
    Club.findOneAndUpdate(
      { slug: filterSlug },
      { $addToSet: { teachers: updateFieldTeacher } }, // Use mongoose operator to insert this club
      // teacher element into the array of teachers
      { new: true }, // enable return the newly updated club object
      (err, club) => {
        if (err) {
          throw new BadRequest('Bad Request', `${err}`);
        } else if (club === null) throw new NotFound(`Not found: ${filterSlug}`);
        else res.status(200).send(club);
      },
    );
  } catch (err) {
    next(err);
  }
});

/**
 * Delete one in the club executives array in a particular club.
 * Pass a slug in the param to query that specific club
 *
 * @property {string} slug -> slug of the club object to be updated
 * @return {Club} club -> the new club object that is updated
 */
router.delete('/club/slug/:slug/executives/delete', jsonParser, async (req, res, next) => {
  const filterSlug = req.params.slug;
  let updateFieldExecutive;
  if (req.body.executive) updateFieldExecutive = req.body.executive;
  try {
    Club.findOneAndUpdate(
      { slug: filterSlug },
      { $pull: { execs: updateFieldExecutive } }, // Use mongoose operator to remove the
      // specific executive from the execs array
      { new: true },
      (err, club) => {
        if (err) {
          throw new BadRequest('Bad Request', `${err}`);
        } else if (club === null) throw new NotFound(`Not found: ${filterSlug}`);
        else res.status(200).send(club);
      },
    );
  } catch (err) {
    next(err);
  }
});

/**
 * Delete one in the club teachers array in a particular club.
 * Pass a slug in the param to query that specific club
 *
 * @property {string} slug -> slug of the club object to be updated
 * @return {Club} club -> the new club object that is updated
 */
router.delete('/club/slug/:slug/teachers/delete', jsonParser, async (req, res, next) => {
  const filterSlug = req.params.slug;
  let updateFieldTeacher;
  if (req.body.teacher) updateFieldTeacher = req.body.teacher;
  try {
    Club.findOneAndUpdate(
      { slug: filterSlug },
      { $pull: { teachers: updateFieldTeacher } }, // Use mongoose operator to remove the
      // specific teacher from the teachers array
      { new: true },
      (err, club) => {
        if (err) {
          throw new BadRequest('Bad Request', `${err}`);
        } else if (club === null) throw new NotFound(`Not found: ${filterSlug}`);
        else res.status(200).send(club);
      },
    );
  } catch (err) {
    next(err);
  }
});










// NEEDS TESTING





router.put('/follow', jsonParser, async (req, res, next) => {
  try {
    const {clubID, userID} = req.body;
    if (!checkExist(clubID)) {
      throw new BadRequest('Missing required field: clubID');
    }
    else if (!checkExist(userID)) {
      throw new BadRequest('Missing required field: userID')
    }
    else {
      const user = await getUser('_id', userID);
      if (checkExist(user)) {
        const club = await getClub('_id', clubID);
        if (checkExist(club)) {
          console.log(club)
          club.members.addToSet(userID);
          club.save().then(() => {
            user.clubs.addToSet(clubID);
            user.save().then(() => {
              res.status(200).json({Message: "Success"});
            })
            .catch((err) => {throw new GeneralError(`${err}`, `${err}`)});
          })
          .catch((err) => {throw new GeneralError(`${err}, ${err}`)});
        }
        else {
          throw new NotFound('Club not found');
        }
      }
      else {
        throw new NotFound('User not found')
      }
    }
  }
  catch (err) {
    next(err);
  }
})

router.put('/unfollow', jsonParser, async (req,res, next) => {
  try {
    const {userID, clubID} = req.body;
    if (!checkExist(userID)) {
      throw new BadRequest('Missing required field: userID');
    }
    else if (!checkExist(clubID)) {
      throw new BadRequest('Missing required field: clubID');
    }
    else {
      const user = await getUser('_id', userID);
      if (checkExist(user)) {
        const club = await getClub('_id', clubID);
        if (checkExist(club)) {
          club.members.pull(userID);
          club.save().then(() => {
            user.clubs.pull(clubID);
            user.save().then(() => {
              res.status(200).json({Message: "Success"});
            })
            .catch((err) => {throw new GeneralError(`${err}, ${err}`)})
          })
          .catch((err) => {throw new GeneralError(`${err}, ${err}`)});
        }
        else {
          res.status(404).json('Club not found');
        }
      }
      else {
        res.status(404).json('User not found');
      }
    }
  }
  catch(err) {next(err)}
})


router.put('/favorite', jsonParser, async (req, res, next) => {
  try {
    const {userID, clubID} = req.body;
    
    if (!checkExist(userID)) throw new BadRequest('Missing required field: userID');
    else if (!checkExist(clubID)) throw new BadRequest('Missing required field: clubID');

    else {
      const user = await getUser('_id', userID);
      if (checkExist(user)) {
        const club = await getClub('_id', clubID);
        if (checkExist(club)) {
          user.favorite_clubs.addToSet(clubID);
          user.save().then(() => {
            res.status(200).json({Message: "Success"});
          })
          .catch((err) => {throw new GeneralError(`${err} , ${err}`)})
        }
        else throw new NotFound('Club not found');
      }
      else throw new NotFound('User not found');
    }
  }
  catch (err) {next(err)};
});

router.put('/unfavorite', jsonParser, async (req, res, next) => {
  try {
    const {userID, clubID} = req.body;
    
    if (!checkExist(userID)) throw new BadRequest('Missing required field: userID');
    else if (!checkExist(clubID)) throw new BadRequest('Missing required field: clubID');

    else {
      const user = await getUser('_id', userID);
      if (checkExist(user)) {
        const club = await getClub('_id', clubID);
        if (checkExist(club)) {
          user.favorite_clubs.pull(clubID);
          user.save().then(() => {
            res.status(200).json({Message: "Success"});
          })
          .catch((err) => {throw new GeneralError(`${err} , ${err}`)})
        }
        else throw new NotFound('Club not found');
      }
      else throw new NotFound('User not found');
    }
    const user = await getUser('_id', userID)
  }
  catch (err) {next(err)};
})

router.put('/add-flair', jsonParser, async (req, res, next) => {
  try {
    const {admin, flair, club} = req.body;
    if (!checkExist(admin)) throw new BadRequest('Missing required field: admin');
    else if (!checkExist(flair)) throw new BadRequest('Missing required field: flair');
    else if (!checkExist(club)) throw new BadRequest('Missing required field: club');
    else {
      const user = await getUser('_id', admin);
      if (checkExist(user)) {
        const tmpClub = await getClub('_id', club);
        if (checkExist(tmpClub)) {
          if (checkExist(tmpClub.execs.find(admin)) || tmpClub.teacher===admin) {
            if (checkExist(tmpClub.flairs.find(flair))) throw new Conflict('Resource conflict: flair already exists');
            else {
              tmpClub.flairs.addToSet(flair);
              tmpClub.save().then(() => {res.status(200).json({Message: "Success"})})
              .catch((err) => {throw new GeneralError(`${err}`, `${err}`)})
            }
          }
          else throw new Forbidden('You are not authorized to this operation');
        }
        else throw new NotFound('Club not found');
      }
      else throw new NotFound('User not found');
    }
  }
  catch(err) {next(err)}
})


module.exports = router;
